name: YT subtitle test (single video)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Set video under test
        run: |
          echo "VIDEO_ID=F1fBsUms8JE" >> $GITHUB_ENV   # <-- change this ID to test others
          echo "VIDEO_URL=https://www.youtube.com/watch?v=F1fBsUms8JE" >> $GITHUB_ENV

      - name: Set up Python + yt-dlp
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Restore cookies.txt
        run: |
          if [ -z "${{ secrets.YT_COOKIES_B64 }}" ]; then
            echo "ERROR: Missing YT_COOKIES_B64 secret"; exit 1
          fi
          printf "%s" "${{ secrets.YT_COOKIES_B64 }}" | base64 -d > cookies.txt
          echo "---- cookies.txt head ----"
          head -n 10 cookies.txt || true
          echo "--------------------------"
          # Sanity: must contain .youtube.com lines
          if ! grep -E "youtube\.com" cookies.txt >/dev/null 2>&1; then
            echo "ERROR: cookies.txt has no youtube.com entries"; exit 1
          fi

      - name: Try android client (verbose)
        run: |
          yt-dlp -v \
            --cookies cookies.txt \
            --skip-download \
            --write-sub --write-auto-sub \
            --sub-langs "en,*en,all" \
            --sub-format vtt \
            --extractor-args "youtube:player_client=android" \
            --output "%(title)s [%(id)s].%(ext)s" \
            "$VIDEO_URL" || true
          ls -la || true

      - name: Try tvhtml5 client (verbose)
        run: |
          yt-dlp -v \
            --cookies cookies.txt \
            --skip-download \
            --write-sub --write-auto-sub \
            --sub-langs "en,*en,all" \
            --sub-format vtt \
            --extractor-args "youtube:player_client=tvhtml5" \
            --output "%(title)s [%(id)s].%(ext)s" \
            "$VIDEO_URL" || true
          ls -la || true

      - name: Try web client (verbose)
        run: |
          yt-dlp -v \
            --cookies cookies.txt \
            --skip-download \
            --write-sub --write-auto-sub \
            --sub-langs "en,*en,all" \
            --sub-format vtt \
            --extractor-args "youtube:player_client=web" \
            --output "%(title)s [%(id)s].%(ext)s" \
            "$VIDEO_URL" || true
          ls -la || true
