name: Pull YouTube transcripts

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install youtube-transcript-api yt-dlp tqdm

      - name: Pull playlist items and transcripts
        env:
          PLAYLIST_URL: "https://www.youtube.com/playlist?list=PLstjectj9BFgWGjHn4y2oygN34oFpSPjR"
        run: |
          python scripts/pull_transcripts.py "$PLAYLIST_URL"

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create paths if missing
          mkdir -p transcripts

          # Stage only what exists, avoid pathspec errors
          [ -e transcripts.csv ] && git add transcripts.csv || true
          [ -e transcripts.jsonl ] && git add transcripts.jsonl || true
          git add transcripts/* || true

          git status

          git commit -m "Update transcripts" || echo "No changes"
          git push
